export { default as depsrc } from './src/depsrc.mjs'
export { default as package } from './src/package.mjs'
export { default as mocharc } from './src/mocharc.mjs'
export { default as jsconfig } from './src/jsconfig.mjs'
export { default as tsconfig } from './src/tsconfig.mjs'
export { default as eslintrc } from './src/eslintrc.mjs'
export { default as babelrc } from './src/babelrc.mjs'
